# Generated by Django 5.0.6 on 2024-06-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='freezingBanco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataFBI', models.DateField()),
                ('dataFBF', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='freezingCartoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataFCI', models.DateField()),
                ('dataFCF', models.DateField()),
            ],
        ),
    ]
