# Generated by Django 5.0.6 on 2024-06-25 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0002_freezingbanco_freezingcartoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreezingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('environment', models.CharField(choices=[('card', 'Cartão'), ('bank', 'Banco')], max_length=4)),
                ('color', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='freezingBanco',
        ),
        migrations.DeleteModel(
            name='freezingCartoes',
        ),
    ]
