# Generated by Django 5.0.6 on 2024-06-27 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0003_freezingperiod_delete_freezingbanco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freezingperiod',
            name='color',
            field=models.CharField(max_length=7),
        ),
    ]
