# Generated by Django 5.0.6 on 2024-06-27 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0004_alter_freezingperiod_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freezingperiod',
            name='color',
            field=models.CharField(max_length=15),
        ),
    ]
